"""Test code generation command."""

import ast
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(sys.version_info < (3, 13), reason="Verify only on the latest version")


def _get_decorator_name(func: ast.FunctionDef) -> str | None:
    if not func.decorator_list:
        return None
    decorator = func.decorator_list[0]
    if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name):
        return decorator.func.id
    return None


def _get_decorator_args(func: ast.FunctionDef) -> list[ast.expr]:
    decorator = func.decorator_list[0]
    if isinstance(decorator, ast.Call):
        return decorator.args
    return []


def _get_step_text(func: ast.FunctionDef) -> str | None:
    args = _get_decorator_args(func)
    if args and isinstance(args[0], ast.Constant):
        return args[0].value
    return None


def _has_raise_not_implemented(func: ast.FunctionDef) -> bool:
    return any(isinstance(stmt, ast.Raise) for stmt in func.body)


def _get_func_docstring(func: ast.FunctionDef) -> str | None:
    return ast.get_docstring(func)


def test_generate(testdir):
    """Test if the code is generated by a given feature."""
    features = testdir.mkdir("scripts")
    feature = features.join("generate.feature")
    feature.write_text(
        # language=gherkin
        """\
        Feature: Code generation

            Scenario: Given and when using the same fixture should not evaluate it twice
                Given I have an empty list
                And 1 have a fixture (appends 1 to a list) in reuse syntax

                When I use this fixture

                Then my list should be [1]
        """,
        "utf-8",
        ensure=True,
    )

    result = testdir.runpytest("--generate", "--feature", str(Path("scripts", "generate.feature")))
    code = result.stdout.str()
    tree1 = ast.parse(code)
    tree = tree1

    assert ast.get_docstring(tree) == "Code generation feature tests."

    imports = [node for node in ast.walk(tree) if isinstance(node, (ast.Import, ast.ImportFrom))]
    import_names = sorted(
        (import_node.module, sorted(alias.name for alias in import_node.names))
        for import_node in imports
        if isinstance(import_node, ast.ImportFrom)
    )
    assert ("pathlib", ["Path"]) in import_names
    assert ("pytest_bdd", ["given", "scenario", "step", "then", "when"]) in import_names

    top_level_functions = [node1 for node1 in ast.iter_child_nodes(tree) if isinstance(node1, ast.FunctionDef)]
    assert len(top_level_functions) == 5

    scenario_func = top_level_functions[0]
    assert _get_decorator_name(scenario_func) == "scenario"
    scenario_args = _get_decorator_args(scenario_func)
    assert len(scenario_args) == 2
    assert isinstance(scenario_args[0], ast.Call)
    assert isinstance(scenario_args[0].func, ast.Name)
    assert scenario_args[0].func.id == "Path"
    assert isinstance(scenario_args[0].args[0], ast.Constant)
    assert scenario_args[0].args[0].value == "scripts/generate.feature"
    assert isinstance(scenario_args[1], ast.Constant)
    assert scenario_args[1].value == "Given and when using the same fixture should not evaluate it twice"

    step_funcs = top_level_functions[1:]
    step_decorators = {_get_decorator_name(f) for f in step_funcs}
    assert step_decorators == {"given", "when", "then"}

    given_funcs = [f for f in step_funcs if _get_decorator_name(f) == "given"]
    assert len(given_funcs) == 2
    given_texts = {_get_step_text(f) for f in given_funcs}
    assert given_texts == {
        "I have an empty list",
        "1 have a fixture (appends 1 to a list) in reuse syntax",
    }

    when_funcs = [f for f in step_funcs if _get_decorator_name(f) == "when"]
    assert len(when_funcs) == 1
    assert _get_step_text(when_funcs[0]) == "I use this fixture"

    then_funcs = [f for f in step_funcs if _get_decorator_name(f) == "then"]
    assert len(then_funcs) == 1
    assert _get_step_text(then_funcs[0]) == "my list should be [1]"

    for func in step_funcs:
        assert _get_func_docstring(func) is not None
        assert _has_raise_not_implemented(func)


def test_generate_with_quotes(testdir):
    """Test that code generation escapes quote characters properly."""
    testdir.makefile(
        ".feature",
        # language=gherkin
        generate_with_quotes="""\
        Feature: Handling quotes in code generation

            Scenario: A step definition with quotes should be escaped as needed
                Given I have a fixture with 'single' quotes
                And I have a fixture with "double" quotes
                And I have a fixture with single-quote '''triple''' quotes
                And I have a fixture with double-quote \"""triple\""" quotes

                When I generate the code

                Then The generated string should be written
        """,
    )

    result = testdir.runpytest("--generate", "--feature", "generate_with_quotes.feature")
    code = result.stdout.str()
    tree1 = ast.parse(code)
    tree = tree1

    assert ast.get_docstring(tree) == "Handling quotes in code generation feature tests."

    funcs = [node for node in ast.iter_child_nodes(tree) if isinstance(node, ast.FunctionDef)]
    assert len(funcs) == 7

    scenario_func = funcs[0]
    assert _get_decorator_name(scenario_func) == "scenario"

    step_funcs = funcs[1:]
    step_decorators = {_get_decorator_name(f) for f in step_funcs}
    assert step_decorators == {"given", "when", "then"}

    given_funcs = [f for f in step_funcs if _get_decorator_name(f) == "given"]
    assert len(given_funcs) == 4
    given_texts = {_get_step_text(f) for f in given_funcs}
    assert "I have a fixture with 'single' quotes" in given_texts
    assert 'I have a fixture with "double" quotes' in given_texts
    assert "I have a fixture with single-quote '''triple''' quotes" in given_texts
    assert 'I have a fixture with double-quote """triple""" quotes' in given_texts

    when_funcs = [f for f in step_funcs if _get_decorator_name(f) == "when"]
    assert len(when_funcs) == 1
    assert _get_step_text(when_funcs[0]) == "I generate the code"

    then_funcs = [f for f in step_funcs if _get_decorator_name(f) == "then"]
    assert len(then_funcs) == 1
    assert _get_step_text(then_funcs[0]) == "The generated string should be written"

    for func in step_funcs:
        assert _get_func_docstring(func) is not None
        assert _has_raise_not_implemented(func)


def test_unicode_characters(testdir):
    """Test generating code with unicode characters.

    Primary purpose is to ensure compatibility with Python2.
    """
    testdir.makefile(
        ".feature",
        # language=gherkin
        unicode_characters="""\
            Feature: Generating unicode characters

                Scenario: Calculating the circumference of a circle
                    Given We have a circle
                    When We want to know its circumference
                    Then We calculate 2 * pi * r
            """,
    )

    result = testdir.runpytest("--generate", "--feature", "unicode_characters.feature")
    code = result.stdout.str()
    tree1 = ast.parse(code)
    tree = tree1

    assert ast.get_docstring(tree) == "Generating unicode characters feature tests."

    funcs = [node for node in ast.iter_child_nodes(tree) if isinstance(node, ast.FunctionDef)]
    assert len(funcs) == 4

    scenario_func = funcs[0]
    assert _get_decorator_name(scenario_func) == "scenario"

    step_funcs = funcs[1:]
    step_decorators = {_get_decorator_name(f) for f in step_funcs}
    assert step_decorators == {"given", "when", "then"}

    given_funcs = [f for f in step_funcs if _get_decorator_name(f) == "given"]
    assert len(given_funcs) == 1
    assert _get_step_text(given_funcs[0]) == "We have a circle"

    when_funcs = [f for f in step_funcs if _get_decorator_name(f) == "when"]
    assert len(when_funcs) == 1
    assert _get_step_text(when_funcs[0]) == "We want to know its circumference"

    then_funcs = [f for f in step_funcs if _get_decorator_name(f) == "then"]
    assert len(then_funcs) == 1
    assert _get_step_text(then_funcs[0]) == "We calculate 2 * pi * r"

    for func in step_funcs:
        assert _get_func_docstring(func) is not None
        assert _has_raise_not_implemented(func)
