from typing import Any

class ConfigFactory:
    @staticmethod
    def parse_string(s: str) -> Any: ...
    @staticmethod
    def parse_file(path: Any) -> Any: ...
    @staticmethod
    def parse_URL(url: str) -> Any: ...

class HOCONConverter:
    @staticmethod
    def to_json(config: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def to_yaml(config: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def to_properties(config: Any, **kwargs: Any) -> str: ...
    @staticmethod
    def convert(config: Any, format: str, **kwargs: Any) -> str: ...
