class TagExpressionParser:
    def __init__(self) -> None: ...
    def evaluate(self, tags: list[str]) -> bool: ...
    @staticmethod
    def parse(infix_expression: str) -> TagExpressionParser: ...

class TagExpressionError(Exception): ...
