# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^.*\\.rst$"
      - id: end-of-file-fixer
        exclude: "^.*\\.rst$"
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.5.0"
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
  - repo: local
    hooks:
      - id: generate-feature-doc
        name: generate-feature-doc
        # language=python
        entry: |
          python -c "
          from subprocess import run as run_unchecked, CalledProcessError
          from sys import exit, executable as python
          run = lambda *args: run_unchecked(args, check=True, shell=True)
          try:
              run(python, '-m', 'ensurepip', '--upgrade')
              run(python, '-m', 'pip', 'install', '.[doc-gen]')
              run(
                  python,
                  'src/pytest_bdd/script/bdd_tree_to_rst.py',
                  'features',
                  'docs/features'
              )
          except CalledProcessError as e:
              exit(e.returncode)
          "
        language: python
        pass_filenames: false
      - id: mypy-tox
        name: mypy
        # language=python
        entry: |
          python -c "
          from subprocess import run as run_unchecked, CalledProcessError
          from sys import exit, executable as python
          run = lambda *args: run_unchecked(args, check=True, shell=True)
          try:
              run(python, '-m', 'ensurepip', '--upgrade')
              run(python, '-m', 'pip', 'install', '.[testenv]')
              run(python, '-m', 'tox', '-e', 'py313-pytestlatest-mypy', '--')
          except CalledProcessError as e:
              exit(e.returncode)
          "
        language: python
        pass_filenames: false
