[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
authors = [
  {name = "Oleg Pidsadnyi", email = "oleg.pidsadnyi@gmail.com"},
  {name = "Anatoly Bubenkov", email = "bubenkoff@gmail.com"},
  {name = "Adam Coddington", email = "me@adamcoddington.net"},
  {name = "Albert-Jan Nijburg", email = "albertjan@curit.com"},
  {name = "Alessio Bogon", email = "youtux@gmail.com"},
  {name = "Andrey Makhnach", email = "andrey.makhnach@gmail.com"},
  {name = "Aron Curzon", email = "curzona@gmail.com"},
  {name = "Dmitrijs Milajevs", email = "dimazest@gmail.com"},
  {name = "Dmitry Kolyagin", email = "pauk-slon@users.noreply.github.com"},
  {name = "Florian Bruhin", email = "me@the-compiler.org"},
  {name = "Floris Bruynooghe", email = "flub@devork.be"},
  {name = "Harro van der Klauw", email = "hvdklauw@gmail.com"},
  {name = "Hugo van Kemenade", email = "hugovk@users.noreply.github.com"},
  {name = "Konstantin Goloveshko", email = "kostya.goloveshko@gmail.com"},
  {name = "Laurence Rowe", email = "l@lrowe.co.uk"},
  {name = "Leonardo Santagada", email = "santagada@github.com"},
  {name = "Milosz Sliwinski", email = "sliwinski.milosz@gmail.com"},
  {name = "Michiel Holtkamp", email = "github@elfstone.nl"},
  {name = "Robin Pedersen", email = "ropez@github.com"},
  {name = "Sergey Kraynev", email = "sergejyit@gmail.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Pytest",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13"
]
dependencies = [
  "aiohttp",
  "attrs",
  "certifi",
  "chevron",
  "ci-environment",
  # This is needed until messages become regular PyPi package https://github.com/cucumber/messages/pull/165
  "cuke-messages==0.1.0",
  "cucumber-expressions",
  "decopatch",
  "docopt-ng",
  "filelock",
  "gherkin-official>=24,<30",
  "importlib-metadata;python_version<'3.10.0'",
  "importlib-resources",
  "makefun",
  "Mako",
  "ordered_set",
  "packaging",
  "parse",
  "parse_type>=0.6.0",
  "pathvalidate",
  "py",
  "pydantic>=2.0.3",
  "pytest>=5.2",
  "cucumber-tag-expressions",
  "typing-extensions;python_version<'3.11.0'"
]
description = "BDD for pytest"
license = {file = "LICENSE.rst"}
maintainers = [
  {name = "Konstantin Goloveshko", email = "kostya.goloveshko@gmail.com"}
]
name = "pytest-bdd-ng"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.9"
version = "2.3.1"

[project.entry-points.pytest11]
"pytest-bdd" = "pytest_bdd.plugin.pytest_bdd.entrypoint"

[project.optional-dependencies]
allure = [
  "allure-python-commons",
  "allure-pytest"
]
doc-gen = [
  'docopt-ng',
  'pandoc',
  'panflute',
  'pathlib2',
  'pypandoc'
]
full = [
  "pytest-bdd-ng[allure]",
  "pytest-bdd-ng[doc-gen]",
  "pytest-bdd-ng[struct-bdd]",
  "pytest-bdd-ng[test]",
  "pytest-bdd-ng[testtypes]"
]
struct-bdd = [
  "hjson",
  "json5",
  "pyhocon",
  'tomli;python_version<"3.11.0"',
  "PyYAML",
  "types-PyYAML"
]
test = [
  "allure-python-commons-test",
  "execnet",
  "packaging",
  "PyHamcrest",
  "pytest-httpserver",
  "python-coveralls",
  "pytest-bdd-ng[doc-gen];python_version>='3.13.0'",
  "ruff"
]
testenv = [
  "tox~=4.0",
  "codecov"
]
testtypes = [
  "mypy",
  "types-certifi",
  "types-docopt",
  "types-setuptools"
]

[project.scripts]
bdd_tree_to_rst = "pytest_bdd.script.bdd_tree_to_rst:main"

[project.urls]
Documentation = "https://pytest-bdd-ng.readthedocs.io/en/default/"
Repository = "https://github.com/elchupanebrej/pytest-bdd-ng"

[tool.mypy]
files = "src/pytest_bdd/**/*.py"
install_types = true
non_interactive = true
plugins = [
  "pydantic.mypy"
]
show_error_codes = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "allure_commons.*",
  "allure_pytest.*",
  "attr.*",
  "ci_environment.*",
  "cucumber_expressions.*",
  "cucumber_tag_expressions.*",
  "decopatch.*",
  "execnet.*",
  "gherkin.*",
  "hjson",
  "json5",
  "makefun",
  "mako.*",
  "ordered_set",
  "parse",
  "parse_type.*",
  "pluggy.*",
  "_pytest.*",
  "pyhocon",
  "pytest.*",
  "yaml.*"
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
  ".eggs",
  ".git",
  ".git-rewrite",
  ".mypy_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "__pypackages__",
  "build",
  "dist",
  "venv"
]
# Same as Black.
line-length = 120
# Assume Python 3.9+
target-version = "py39"

[tool.ruff.format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
ignore = [
  "W191",  # tab-indentation
  "E111",  # indentation-with-invalid-multiple
  "E114",  # indentation-with-invalid-multiple-comment
  "E117",  # over-indented
  "D206",  # docstring-tab-indentation
  "D300",  # triple-single-quotes
  "Q000",  # bad-quotes-inline-string
  "Q001",  # bad-quotes-multiline-string
  "Q002",  # bad-quotes-docstring
  "Q003",  # avoidable-escaped-quote
  "COM812",  # missing-trailing-comma
  "COM819",  # prohibited-trailing-comma
  "ISC002",  # multi-line-implicit-string-concatenation
  "E501",  # line too long, handled by formatter
  "TC006"  # https://youtrack.jetbrains.com/issue/PY-46326/Pycharm-does-not-recognize-imports-used-for-typing.cast-when-they-are-incased-in-a-string-and-removing-them-when-optimizing]
]
# Enable pycodestyle (`E`), Pyflakes (`F`), and isort (`I`) codes
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "ARG", "SIM", "TCH", "TID", "Q"]
unfixable = []

[tool.ruff.lint.isort]
# Like isort, sort imports using a single line after the import block.
force-single-line = false
# Like isort, separate sections with a blank line.
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
