[pytest]
testpaths = tests
bdd_features_base_dir = features/
addopts = -p pytester
filterwarnings =
    error
    ignore::DeprecationWarning
    ignore::ImportWarning
markers =
    deprecated: mark test testing deprecated API
    deficient: mark test with non-full coverage
    surplus: mark test testing non-standard API
    technical_nonconvertible: mark technical regression tests that must remain in pytest suite
