# ruff: noqa: B018, D100, F821

fixturemanager  # unused variable (src\pytest_bdd\compatibility\pytest\__init__.py:135)
FunctionType  # unused import (src\pytest_bdd\hook.py:21)
GherkinDocumentWithURI  # unused import (src\pytest_bdd\model\feature_binding.py:32)
AttrsInstance  # unused import (src\pytest_bdd\model\message_converter.py:10)
Match  # unused import (src\pytest_bdd\parsers.py:9)
event  # unused variable (src\pytest_bdd\plugin\gherkin_message_reporter\message_stream.py:39)
Traversable  # unused import (src\pytest_bdd\plugin\gherkin_message_reporter\session.py:27)
fixturefunc  # unused variable (src\pytest_bdd\plugin\pickle_runner\plugin.py:62)
nextitem  # unused variable (src\pytest_bdd\plugin\pickle_runner\plugin.py:185)
module_path  # unused variable (src\pytest_bdd\plugin\scenario_test_collector\plugin.py:284)
manager  # unused variable (src\pytest_bdd\plugin\scenario_test_collector\plugin.py:309)
module_path  # unused variable (src\pytest_bdd\plugin\struct_bdd\plugin.py:169)
FunctionType  # unused import (src\pytest_bdd\steps\definition.py:33)
CodeType  # unused import (src\pytest_bdd\util\inspect_extra.py:11)
FrameType  # unused import (src\pytest_bdd\util\inspect_extra.py:11)
FunctionType  # unused import (src\pytest_bdd\util\inspect_extra.py:11)
MethodType  # unused import (src\pytest_bdd\util\inspect_extra.py:11)
TracebackType  # unused import (src\pytest_bdd\util\inspect_extra.py:11)
