---
services:
  controller:
    image: pytest-bdd-remote-xdist-controller:local
    build:
      context: ../../../../..
      dockerfile: >-
        src/pytest_bdd_testing/resource/docker/remote_xdist/controller.Dockerfile
    entrypoint: ["sleep", "infinity"]
    environment:
      PYTEST_REMOTE_MODE: ${PYTEST_REMOTE_MODE:-socket}
      PYTEST_BDD_TRANSPORT_FAIL_WORKERS: ${PYTEST_BDD_TRANSPORT_FAIL_WORKERS:-}
      REPORT_PATH: /artifacts/${REPORT_NAME}
      VERIFY_REPORT_MODE: ${VERIFY_REPORT_MODE:-success}
      PYTEST_REMOTE_EXTRA_ARGS: ${PYTEST_REMOTE_EXTRA_ARGS:-}
      PYTEST_REMOTE_FAKE_NODE_ROOT: ${PYTEST_REMOTE_FAKE_NODE_ROOT:-}
      PYTEST_REMOTE_FAKE_NODE_CAPTURE_DIR: >-
        ${PYTEST_REMOTE_FAKE_NODE_CAPTURE_DIR:-}
    depends_on:
      - proxy
      - worker1
      - worker2
    volumes:
      - ./artifacts:/artifacts

  proxy:
    image: pytest-bdd-remote-xdist-worker:local
    build:
      context: ../../../../..
      dockerfile: >-
        src/pytest_bdd_testing/resource/docker/remote_xdist/worker.Dockerfile
    environment:
      PYTEST_REMOTE_MODE: proxy
    depends_on:
      - worker1

  worker1:
    image: pytest-bdd-remote-xdist-worker:local
    build:
      context: ../../../../..
      dockerfile: >-
        src/pytest_bdd_testing/resource/docker/remote_xdist/worker.Dockerfile
    environment:
      PYTEST_REMOTE_MODE: ${PYTEST_REMOTE_MODE:-socket}

  worker2:
    image: pytest-bdd-remote-xdist-worker:local
    build:
      context: ../../../../..
      dockerfile: >-
        src/pytest_bdd_testing/resource/docker/remote_xdist/worker.Dockerfile
    environment:
      PYTEST_REMOTE_MODE: ${PYTEST_REMOTE_MODE:-socket}
    depends_on:
      - worker1
