from typing import Any

class Stash:
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def setdefault(self, key: Any, default: Any = ...) -> Any: ...
