from typing import Any

class Parser:
    def __init__(self, ast_builder: Any | None = None) -> None: ...
    def parse(self, token_scanner_or_str: Any, token_matcher: Any | None = None) -> Any: ...

class AstBuilder:
    def __init__(self, id_generator: Any | None = None) -> None: ...
