from typing import Any

class WorkerInteractor:
    def __init__(self, config: Any, channel: Any) -> None: ...
    def setup(self) -> None: ...
    def ensure_teardown(self) -> None: ...
    def shutdown(self) -> None: ...

class WorkerInfo: ...
class TestQueue: ...
class Marker: ...
class Producer: ...
