from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class OrderedSet(Generic[_T]):
    def __init__(self, iterable: Any = ...) -> None: ...
    def add(self, element: _T) -> None: ...
    def discard(self, element: _T) -> None: ...
    def __contains__(self, element: _T) -> bool: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
