from typing import Any

class TerminalReporter:
    config: Any
    verbosity: int
    stats: dict[str, list[Any]]
    _tw: Any
    def __init__(self, config: Any) -> None: ...
    def ensure_newline(self) -> None: ...
    def write_sep(self, sep: str, title: str | None = ..., fullwidth: bool | None = ..., **kwargs: Any) -> None: ...
    def write(self, s: str, **kwargs: Any) -> None: ...
    def write_line(self, s: str, **kwargs: Any) -> None: ...
    def section(self, title: str, sep: str = ..., **kwargs: Any) -> None: ...
    def line(self, s: str, **kwargs: Any) -> None: ...
    def flush(self) -> None: ...
    def hasopt(self, opt: str) -> bool: ...
    def pytest_runtest_logreport(self, report: Any) -> Any: ...
