"""Provide src.pytest_bdd.model package helpers."""

from .execution_message_adapter import ExecutionMessageAdapter, ExecutionProjection
from .message_baseline_diff import (
    WEEKLY_CADENCE,
    BaselineComparisonSchedule,
    BaselineDiffExecutionResult,
    BaselineDiffRecord,
    build_baseline_diff,
    execute_weekly_baseline_diff,
    is_weekly_run_due,
    next_weekly_run_at,
)
from .message_capability import (
    RELEVANT_IMPACTS,
    MessageCapability,
    capability_is_relevant,
    classify_capability_relevance,
)
from .message_capability_inventory import CapabilitySyncResult, sync_capability_inventory
from .message_converter import governance_value_to_dict, message_converter
from .message_governance_checklist import (
    DEFAULT_CHECKLIST_NAME,
    GovernanceChecklist,
    GovernanceChecklistEntry,
    build_governance_checklist,
    render_checklist_markdown,
)
from .message_outcome_mapping import (
    MATRIX_PROFILE_FIXED_RELEASE_READINESS_V1,
    REQUIRED_MATRIX_STATUSES,
    MappingValidationResult,
    ObservedOutcome,
    OutcomeMappingRule,
    find_matching_rules,
    outcome_key,
    resolve_outcome_mapping,
    validate_outcome_mappings,
)
from .message_serialization import MessageSerializationProfile
from .message_status_governance import (
    CAPABILITY_STATUSES,
    LEGACY_STATUS_ALIASES,
    MANDATORY_EVIDENCE_FIELDS,
    NON_IMPLEMENTED_STATUSES,
    RELEASE_BLOCKER_STATUSES,
    BlockerEvaluationResult,
    CapabilityDecision,
    DecisionValidationResult,
    StatusUniquenessResult,
    ensure_single_status_per_capability,
    evaluate_release_blockers,
    is_release_blocker_status,
    missing_required_evidence_fields,
    normalize_capability_status,
    validate_capability_decision,
)
from .message_validation import (
    ALLOWED_IMPLEMENTATION_STATUSES,
    MessageValidationResult,
    MessageValidationViolation,
    collect_observed_outcomes,
    default_outcome_mapping_rules,
    observed_outcome_from_envelope,
    validate_envelope_against_schema,
    validate_envelope_dict_against_schema,
    validate_envelope_shape,
    validate_message_stream,
)
from .scenario_run import (
    ActiveObjectSet,
    ContextErrorState,
    ExternalApiCompatibilityRecord,
    HookPhase,
    LifecycleObjectRef,
    ReferenceResolverState,
    ReportingContextSnapshot,
    ReportingLifecycleState,
    Run,
    RunNode,
    RunStage,
    RunStatus,
    ScenarioRun,
)

__all__ = [
    "ALLOWED_IMPLEMENTATION_STATUSES",
    "CAPABILITY_STATUSES",
    "DEFAULT_CHECKLIST_NAME",
    "LEGACY_STATUS_ALIASES",
    "MANDATORY_EVIDENCE_FIELDS",
    "MATRIX_PROFILE_FIXED_RELEASE_READINESS_V1",
    "NON_IMPLEMENTED_STATUSES",
    "RELEASE_BLOCKER_STATUSES",
    "RELEVANT_IMPACTS",
    "REQUIRED_MATRIX_STATUSES",
    "WEEKLY_CADENCE",
    "ActiveObjectSet",
    "BaselineComparisonSchedule",
    "BaselineDiffExecutionResult",
    "BaselineDiffRecord",
    "BlockerEvaluationResult",
    "CapabilityDecision",
    "CapabilitySyncResult",
    "ContextErrorState",
    "DecisionValidationResult",
    "ExecutionMessageAdapter",
    "ExecutionProjection",
    "ExternalApiCompatibilityRecord",
    "GovernanceChecklist",
    "GovernanceChecklistEntry",
    "HookPhase",
    "LifecycleObjectRef",
    "MappingValidationResult",
    "MessageCapability",
    "MessageSerializationProfile",
    "MessageValidationResult",
    "MessageValidationViolation",
    "ObservedOutcome",
    "OutcomeMappingRule",
    "ReferenceResolverState",
    "ReportingContextSnapshot",
    "ReportingLifecycleState",
    "Run",
    "RunNode",
    "RunStage",
    "RunStatus",
    "ScenarioRun",
    "StatusUniquenessResult",
    "build_baseline_diff",
    "build_governance_checklist",
    "capability_is_relevant",
    "classify_capability_relevance",
    "collect_observed_outcomes",
    "default_outcome_mapping_rules",
    "ensure_single_status_per_capability",
    "evaluate_release_blockers",
    "execute_weekly_baseline_diff",
    "find_matching_rules",
    "governance_value_to_dict",
    "is_release_blocker_status",
    "is_weekly_run_due",
    "message_converter",
    "missing_required_evidence_fields",
    "next_weekly_run_at",
    "normalize_capability_status",
    "observed_outcome_from_envelope",
    "outcome_key",
    "render_checklist_markdown",
    "resolve_outcome_mapping",
    "sync_capability_inventory",
    "validate_capability_decision",
    "validate_envelope_against_schema",
    "validate_envelope_dict_against_schema",
    "validate_envelope_shape",
    "validate_message_stream",
    "validate_outcome_mappings",
]
