from collections.abc import Callable
from typing import Any, TypeVar, overload

from typing_extensions import ParamSpec

_P = ParamSpec("_P")
_R = TypeVar("_R")

class Result:
    result: Any
    def force_result(self, result: Any) -> None: ...
    def get_result(self) -> Any: ...

class PluginManager:
    def register(self, plugin: object, name: str | None = ...) -> None: ...
    def unregister(self, plugin: object) -> None: ...
    def get_plugin(self, name: str) -> object | None: ...
    def is_registered(self, plugin: object) -> bool: ...
    def list_name_plugin(self) -> list[tuple[str, object]]: ...
    def list_plugin_distinfo(self) -> list[tuple[object, Any]]: ...
    def has_package(self, name: str) -> bool: ...
    def add_hookspecs(self, module_or_class: object) -> None: ...
    def check_pending(self) -> None: ...
    def load_setuptools_entrypoints(self, group: str, name: str | None = ...) -> int: ...
    def consider_module(self, modname: str) -> object: ...
    def consider_env(self) -> None: ...
    def import_plugin(self, modname: str, consider_entry_points: bool = ...) -> object: ...
    def get_hookcallers(self, plugin: object) -> list[Any] | None: ...
    def subset_hook_caller(self, name: str, remove_plugins: list[object]) -> Any: ...

class HookimplMarker:
    @overload
    def __call__(self, function: Callable[_P, _R], /) -> Callable[_P, _R]: ...
    @overload
    def __call__(
        self,
        *,
        specname: str | None = ...,
        optionalhook: bool = ...,
        tryfirst: bool = ...,
        trylast: bool = ...,
        hookwrapper: bool = ...,
    ) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...
    @overload
    def __call__(
        self,
        specname: str | None,
        optionalhook: bool = ...,
        tryfirst: bool = ...,
        trylast: bool = ...,
        hookwrapper: bool = ...,
    ) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...

class HookspecMarker:
    @overload
    def __call__(self, function: Callable[_P, _R], /) -> Callable[_P, _R]: ...
    @overload
    def __call__(
        self,
        *,
        firstresult: bool = ...,
        historic: bool = ...,
        warn_on_impl: Any = ...,
    ) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...
    @overload
    def __call__(
        self,
        firstresult: bool = ...,
        historic: bool = ...,
        warn_on_impl: Any = ...,
    ) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...

class _Result: ...
class _ResultBase: ...

hookimpl: HookimplMarker
hookspec: HookspecMarker
set_trace: Any
