from typing import Any

class Parser:
    def addini(self, name: str, help: str, type: str | None = ..., default: Any = ...) -> Any: ...
    def getgroup(self, name: str, description: str = ...) -> Any: ...
